services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: backloggi
      POSTGRES_PASSWORD: backloggi
      POSTGRES_DB: backloggi
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
